spring.application.name=ticketnest-backend

spring.datasource.url=jdbc:mysql://localhost:3306/ticketnest
spring.datasource.username=
spring.asource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable docker compose
spring.docker.compose.enabled=false

server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
springdoc.swagger-ui.path=/swagger